In [1]:
import pandas as pd

In [66]:
df = pd.read_csv(r'C:\Users\bitse\YandexDisk\Rushim\rushim\w_3.csv')

In [67]:
df

,product,category,price,trademark,country,description,CAS,INCI,manufacturer,packing
0,Изопропиловый спирт (Пропанол-2),Реактивы и хим. сырье,4260,NaN,NaN,NaN,NaN,NaN,NaN,упаков
1,Калий фосфорнокислый 2-замещенный 3 водн,Реактивы и хим. сырье,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Натрий салициловокислый,Реактивы и хим. сырье,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Крахмал текстильный Aprin,Реактивы и хим. сырье,110,NaN,NaN,NaN,NaN,NaN,NaN,упаков
4,Крахмал водорастворимый,Реактивы и хим. сырье,798,NaN,NaN,NaN,NaN,NaN,NaN,упаков
...,...,...,...,...,...,...,...,...,...,...
794,Бензилбензоат,Реактивы и хим. сырье,570,NaN,NaN,NaN,NaN,NaN,NaN,упаков
795,Дифениламин имп,Реактивы и хим. сырье,2900,NaN,NaN,NaN,NaN,NaN,NaN,упаков
796,Бентонит (глинопорошок для виноделия),Реактивы и хим. сырье,1985,NaN,NaN,NaN,NaN,NaN,NaN,упаков
797,Калий дихромат,Реактивы и хим. сырье,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
798,Уранин А (индикатор,Реактивы и хим. сырье,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [70]:
df_him = df

In [71]:
#df_him.to_excel('result-rushim.xlsx', index=False)

In [6]:
df_1 = pd.read_excel(r'C:\Users\bitse\Desktop\result_rushim_pandas.xlsx')

In [7]:
dup = df_1.drop_duplicates(subset=['product'])

In [10]:
dup

,product,category,price,trademark,country,description,CAS,INCI,manufacturer,packing
0,Изопропиловый спирт (Пропанол-2),Реактивы и хим. сырье,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Калий фосфорнокислый 2-замещенный 3 водн,Реактивы и хим. сырье,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Натрий салициловокислый,Реактивы и хим. сырье,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Крахмал текстильный Aprin,Реактивы и хим. сырье,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Крахмал водорастворимый,Реактивы и хим. сырье,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
789,Трипановый синий,Реактивы и хим. сырье,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
790,Калий сернокислый пиро,Реактивы и хим. сырье,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
791,Изоамиловый спирт,Реактивы и хим. сырье,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
792,Натрий селенистокислый кислый,Реактивы и хим. сырье,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
798,Уранин А (индикатор,Реактивы и хим. сырье,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
dup.to_excel('result_pandas______123.xlsx')